### ISSUE TITLE
[Issue/Bug] In the phone side the streaming vibrate a lot.

### ISSUE THREAD

**Issue by HugoPlacer** [alvr-org/PhoneVR#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this issue has already been addressed in documentation?

- [X] I have read the readme file

### Describe the bug/issue

When I'm in the Steam vr home, the streaming vibrates/jerks but in the pc side it doesn't show up this vibration. I'm using Linux with ALVR v20.4.3 (I tried the recommended version too) with nvidia graphics card.

### Local (your) Time when Issue has occurred

28-10-2023, 12:30:00 Hrs

### How To Reproduce your issue

Install ALVR in linux and connect your phone using phonevr to alvr.

### Expected behaviour

No vibration.

### Screenshots

https://github.com/PhoneVR-Developers/PhoneVR/assets/69766683/107c6204-7a3a-4e3d-befa-4847c2892fe7

### Environment (please complete the following information)

Desktop OS: ArchLinux
Android OS: Android 13
Mobile Device Model: One Plus Nord (Pixel Experience Plus Rom)
ALVR v20.4.3
PhoneVR v1.1.0

### Attached Logs

[alvr_session_log.txt](https://github.com/PhoneVR-Developers/PhoneVR/files/13196113/alvr_session_log.txt)

**Comment by gabe39** [comment]
I've had this problem too, but for some reason it disappeared after I restarted my phone. (I have an AMD card and I'm using windows though)

**Comment by H3wastooshort** [comment]
i have had this problem with 2 different phones

**Comment by 0Human0** [comment]
Might be something with Android 13, I've also got a phone on Android 13 (S22 Ultra)

**Comment by 0Human0** [comment]
Just found while trying to recording the screen on my device stops the shaking immediately when the recording stops

**Comment by Athamanatha** [comment]
I've seen this problem with a Samsung Galaxy S21 FE 5G on Windows 11 with ALVR 20.6.1 and PhoneVR 1.3.0-beta.

**Comment by Athamanatha** [comment]
Here is a video of the jitter/tearing of the video, on the above mentioned configuration, right after I rebooted the phone and SteamVR too. https://drive.google.com/file/d/12HwO74qcgZjUZqrqjir7kWTd1KL9rUiQ/view?usp=drive_link (using Google Drive because of file size)

**Comment by ShootingKing-AM** [comment]
Settings + Stats Page + Logs page Screenshots please, Now when taking stats page SS put the mouse so the Legend of the chart is highlighted

**Comment by VentorNew** [comment]
**### Attached video, screenshots, and log.**
Hi, here's what I could find on this issue. I have a similar problem. I’m not sure what exactly might be useful, so I’ll say everything.

> (I use Google translator; I don’t know how to make a spoiler for screenshots or video)

- Redmi Note 10 5G
- Windows 10
- WiFi 5.0
- GT 1030 video card
- i5 3470 processor
- ALVR 20.6.1
- PhoneVR 1.3.0 -beta


From the very first launch, at first I only had flickering colors on the phone screen, corresponding to the colors from the VR scene.

> https://github.com/PhoneVR-Developers/PhoneVR/assets/61165984/4bcb14b4-28e3-43a2-a402-48d023194023

I disabled "Foveated encoding" and a few other things that were suggested to be disabled in another discussion https://github.com/PhoneVR-Developers/PhoneVR/issues/236#issuecomment-1774064429 . After that, this harsh camera shake appeared. I experimented with the settings and this is half the solution in my case. The shaking seemed to get weaker, but did not go away completely.

> https://github.com/PhoneVR-Developers/PhoneVR/assets/61165984/7e0e4a11-3d46-4e61-a892-4c0032b36683

After that, the next day I decided to start the program and VR again. And..... lo and behold! The picture was smooth. But after restarting the shaking returned.
I left the ALVR settings the same. But on the phone side, I cleared all PhoneVR app data. 
![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/61165984/f44e35a6-615d-4e28-af89-e521db3b49f4)

After this, the image twitching it seems to have disappeared.

> https://github.com/PhoneVR-Developers/PhoneVR/assets/61165984/6f83586d-eafc-4537-b9b2-fadb27d572dd

-
-
-

### **Log**
[session_log_13_27.txt](https://github.com/PhoneVR-Developers/PhoneVR/files/14296728/session_log_13_27.txt)

-
-
-


**Screenshots settings**
![1](https://github.com/PhoneVR-Developers/PhoneVR/assets/61165984/3c748965-71c6-4639-96ec-a3633af1f1f6)
![2](https://github.com/PhoneVR-Developers/PhoneVR/assets/61165984/0de83518-a3ed-4274-a633-0707785f8f62)
![3](https://github.com/PhoneVR-Developers/PhoneVR/assets/61165984/a3088546-6860-4dbc-b424-f5f649f8958e)
![4](https://github.com/PhoneVR-Developers/PhoneVR/assets/61165984/70d2f329-614b-4a63-bb6b-cfc2dde2fd7c)
![5](https://github.com/PhoneVR-Developers/PhoneVR/assets/61165984/73306499-e2be-4ab6-b160-f869a5f684b6)

**Comment by ShootingKing-AM** [comment]
Thanks for the information. You should have also taken the Statistics tab of ALVR screenshots, they have valuable network information

**Comment by arturopitu** [comment]
Poco X3 with crdroid android 13 here, reducing the display fps to 60 helped a lot, maybe there's a bug within there

**Comment by H3wastooshort** [comment]
For me it only is a fromblem when i set my display to a higher framerate. 60fps is fine

**Comment by ShootingKing-AM** [comment]
Seems like i can reproduce this is Foveated encoding is turned off.

**Comment by Ency0810** [comment]
I also has the same problem

my device:
phone: redmi k50 pro (android 14)   MediaTek 9300
PC:windows 11 workstation
CPU:14600kf   
GPU:RTX4070ti super
ALVR 20.6.1
PhoneVR 1.3.0

https://github.com/alvr-org/PhoneVR/assets/65378717/a690b969-08f3-42cc-9c9f-ff16856c5c95
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/5823cad5-774e-4ccf-9ae4-e7d1e8e7c84a)

![image](https://github.com/alvr-org/PhoneVR/assets/65378717/6dc73d3e-63ce-4f6e-88b4-7776241c18b8)
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/d0e7069f-613c-4e43-a1ea-7ac22355364e)
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/96e8a918-005c-4fa3-8c14-7b6f2f146573)
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/1ea8c795-ab4f-48fb-b676-ef742d98860d)
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/26b96542-995f-45a8-bb4b-257c3a75fa71)
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/44ca47f6-e0da-4c2a-9009-27bb8eda57d1)
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/125765d8-f0a1-436d-8d21-cfd94ed6feac)

![image](https://github.com/alvr-org/PhoneVR/assets/65378717/6f69b7d0-010b-4714-8798-7d5c36d1dd4a)
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/4b8e8d0c-762e-4b33-9d85-05387fdccaf9)

![image](https://github.com/alvr-org/PhoneVR/assets/65378717/96dffd81-92f2-4ac0-b48e-d0a121675441)
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/f7344613-5b8f-4b99-8859-82e9a15b3175)
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/d9cff84b-c5f4-420a-958f-60cf57d6c64a)
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/099a9b53-78b2-4723-b000-eeb226fdb8f3)

**Comment by Ency0810** [comment]
![image](https://github.com/alvr-org/PhoneVR/assets/65378717/4ecfc0a8-3a24-4745-af1d-eb7ecc951b79)

**Comment by ShootingKing-AM** [comment]
I think the latest release v2.0.0-beta solve these issues, you dont need to keep foveated encoding option OFF anymore

**Comment by TWTom041** [comment]
Can confirm, fovated encoding on, 60fps works for me, 120fps doesn't though.

**Comment by EdLovecraft** [comment]
same issue, 2.0.0 still has this issue.
