### ISSUE TITLE
[enhancement] Allow manual brightness control when using ALVR

### ISSUE THREAD

**Issue by JEthenoobgamer** [alvr-org/PhoneVR#307]
The app locks the brightness at a 100% when using it with ALVR, which can be too bright for some situations or also contribute to screen burn-in on OLED devices and it overall makes your phone overheat faster. It'll be nice if you could control de brightness manually or at least if it didn't locked itself at a 100%.

**Comment by ShootingKing-AM** [comment]
True, maybe removing the lock will be good, we can adjust brightness with system controls.
