### ISSUE TITLE
[Issue/Bug] Pairing failed! Cause: timeout ... for 5secs

### ISSUE THREAD

**Issue by Muska-Ami** [alvr-org/PhoneVR#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this issue has already been addressed in documentation?

- [X] I have read the readme file

### Describe the bug/issue

When I install PhoneVR, the driver seems not load correctly with log `Pairing failed! Cause: timeout ... for 5secs`
And seem it's doesn't work properly.

### Local (your) Time when Issue has occurred

2024-02-27 15:15:31 CST(+8:00)

### How To Reproduce your issue

1. Install driver
2. Open SteamVR

### Expected behaviour

Connect to SteamVR correctly

### Screenshots

![image](https://github.com/alvr-org/PhoneVR/assets/79651409/f8ebae02-3ab2-41ae-bd19-ab84ef6aae43)
![image](https://github.com/alvr-org/PhoneVR/assets/79651409/12abd003-2ae6-43ca-87da-6f06136a504a)

### Environment (please complete the following information)

- OS: Windows 11 23H2 (22631.2861)
- SteamVR 2.3.5
- CPU: Intel(R) Xeon(R) CPU E5-2666v3 @ 2.90GHz (2 Physical CPU with 20c40t)
- RAM: 16GB DDR3 ECC 1866MHz (2)
- GPU: AMD RX580 2048SP

### Additional context

pvrsettings.json

```json
{
    "enable" : true,
    "game_fps" : 60,
    "video_stream_port" : 15243,
    "pose_stream_port" : 51423,
    "pairing_port" : 12451,
    "connection_timeout" : 5,
    "encoder" : {
        "preset" : "ultrafast",
        "tune" : "zerolatency",
        "qp" : 20,
        "profile" : "baseline"
    }
}
```

### Attached Logs

```sh
15:09:34(351) - 27.02.2024 -- 34 max  ------------------------------------
15:09:34(352) - 27.02.2024 -- 34 000  Getting server
15:09:34(352) - 27.02.2024 -- 34 001  [ServerProvider::Init] Initializing server
15:09:34(354) - 27.02.2024 -- 34 001  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 12451
15:09:39(353) - 27.02.2024 -- 39 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
```

**Comment by ShootingKing-AM** [comment]
Why not use the ALVR server ? Development of PVE-legacy server is not being done presently.

**Comment by Muska-Ami** [comment]
> Why not use the ALVR server ? Development of PVE-legacy server is not being done presently.

Well, I tried ALVR server, but when connected to the phone, the phone screen starts to flicker and twitch and nothing is displayed normally. How can I fix it?

**Comment by ShootingKing-AM** [comment]
maybe related to : https://github.com/alvr-org/PhoneVR/issues/236#issuecomment-1774064429

**Comment by Muska-Ami** [comment]
```
Google Pixel 7 Pro
OS: Android 14
Kernel: Linux 5.10-android
CPU: GS201
GPU: Mali-G710
```
I tried disable `Foveated rendering` and `Clientside foveation`, then the screen displayed correctly but with very violent screen shaking. Does any options can screen shaking?

**Comment by ShootingKing-AM** [comment]
> ```
> Google Pixel 7 Pro
> OS: Android 14
> Kernel: Linux 5.10-android
> CPU: GS201
> RAM: LPDDR5X 12GB
> GPU: Mali-G710
> Screen: 3120x1440 512ppi 120Hz
> ```
> 
> I tried disable `Foveated rendering` and `Clientside foveation`, then the screen displayed correctly but with very violent screen shaking like #240 . Does any options can screen shaking?

for now, WIP. PRs are welcome tho.

**Comment by Muska-Ami** [comment]
All right,,,
