### ISSUE TITLE
[Issue] the 2.7.1alvr is notwoking

### ISSUE THREAD

**Issue by H-Bole** [alvr-org/PhoneVR#332]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is this issue has already been addressed in documentation?

- [X] I have read the readme file

### Describe the bug/issue

Please update the phonevr version to alvr2.7.1. You mentioned in your introduction that the latest support is 2.6.1. I have tried it and it can run normally, but the latest version of alvr has arrived at 2.7.1, and I cannot run it normally

### Local (your) Time when Issue has occurred

15-4-2024，17：55.

### How To Reproduce your issue

alvr2.7.1 and phonevr1.3.0 are not working properly

### Expected behaviour

Normal operation

### Environment (please complete the following information)

win11
redmi K50

**Comment by Ency0810** [comment]
Hello, you say that you can use the 1.3.0b phone vr and alvr 2.6.1 
Do you have met any problem like getting a really compressed and jittery video?
I'm looking forward to your contact.My QQ number is 1292938590

**Comment by H-Bole** [comment]
Actually, I also had problems with 1.3.0, not only video shake, but also white screen, I tried to turn off gaze point rendering and then open Steamvr, which caused my computer to crash, I don't know why, but with alvr2.7.1 version it doesn't crash, but phonevr doesn't work properly

**Comment by H-Bole** [comment]
> Hello, you say that you can use the 1.3.0b phone vr and alvr 2.6.1 
> Do you have met any problem like getting a really compressed and jittery video?
> I'm looking forward to your contact.My QQ number is 1292938590

Actually, I also had problems with 1.3.0, not only video shake, but also white screen, I tried to turn off gaze point rendering and then open Steamvr, which caused my computer to crash, I don't know why, but with alvr2.7.1 version it doesn't crash, but phonevr doesn't work properly

**Comment by Ency0810** [comment]
Now there is a new test apk can connect to the 2.7.1，you can have a try.I still have the same problem，If you success，you can tell me
The download link is in the discord #general

**Comment by ShootingKing-AM** [comment]
master is released now.
