### ISSUE TITLE
The two covered legs cannot be focused[Issue/Bug] Title

### ISSUE THREAD

**Issue by kaze0329** [alvr-org/PhoneVR#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this issue has already been addressed in documentation?

- [X] I have read the readme file

### Describe the bug/issue

My VR headset is XRSPACE. There is no problem connecting to ALVR through PHONEVR. However, the angle of view of the left and right eyes cannot be focused. It seems that the left eye will squint outward. Is there any way to adjust it?

### Local (your) Time when Issue has occurred

2024 年 4 月 28 日 15:30:00

### How To Reproduce your issue

My VR headset is XRSPACE. There is no problem connecting to ALVR through PHONEVR. However, the angle of view of the left and right eyes cannot be focused. It seems that the left eye will squint outward. Is there any way to adjust it?

### Expected behaviour

My VR headset is XRSPACE. There is no problem connecting to ALVR through PHONEVR. However, the angle of view of the left and right eyes cannot be focused. It seems that the left eye will squint outward. Is there any way to adjust it?

### Screenshots

![螢幕擷取畫面 2024-04-29 201742](https://github.com/alvr-org/PhoneVR/assets/44696741/ed4ae42c-d2a8-443a-ac57-9b6d9a514091)

### Environment (please complete the following information)

WINDOWS 11，ANDROID 8，PHONE VR 1.4，ALVR 20.7.1，XRSPACE XR00V1

**Comment by ShootingKing-AM** [comment]
You can check with latest v2.0.0-beta release
