### ISSUE TITLE
java.lang.StackOverflowError: stack size 8188KB

### ISSUE THREAD

**Issue by WavingSpark** [alvr-org/PhoneVR#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this issue has already been addressed in documentation?

- [X] I have read the readme file

### Describe the bug/issue

The app opens fine, but when SteamVR opens on my pc, my phone app crashes showing the message : "java.lang.StackOverflowError: stack size 8188KB"

### Local (your) Time when Issue has occurred

13-July-2024, 16:36 Hrs

### How To Reproduce your issue

Go to "Use PhoneVR(GoogleVR API Legacy Server)

Open SteamVR on your PC

(the phone connects for a second but just shows a black screen with the eye divider thing and then crashes.)

### Expected behaviour

I expected it to connect and be able to play SteamVR games.

### Screenshots

![Screenshot_20240713_164116_PhoneVR](https://github.com/user-attachments/assets/136ac2b0-c5fb-479a-ba64-e88697180a51)

### Environment (please complete the following information)

Desktop OS - Windows 11
Android 14

### Attached Logs

[pvrlog.txt](https://github.com/user-attachments/files/16202174/pvrlog.txt) - DESKTOP

[pvrlog - phone.txt](https://github.com/user-attachments/files/16202179/pvrlog.-.phone.txt)

**Comment by OllieIOW** [comment]
same error here except sometimes it just randomly happens midgame. (win 11, android 14)

**Comment by ShootingKing-AM** [comment]
Why not use ALVR Server ? what device are you using ?

**Comment by WavingSpark** [comment]
> Why not use ALVR Server ? what device are you using ?

Using a Samsung A7

im not using ALVR server cause it dosent connect and PhoneVR works on my older phone but the screen quality is TRASH

**Comment by ShootingKing-AM** [comment]
I am assuming older phone screen quality is trash (or the alvr stream video quality is trash?)

Alvr-phonevr is actively being maintained, suggest you to use alvr-phonevr setup and share logs as to why it's not getting connected. Developing legacy phonevr server and fixing it's issues will take time :c

**Comment by WavingSpark** [comment]
the older phone screen quality is trash, ill post the alvr logs as soon as possible.

**Comment by WavingSpark** [comment]
here u go 

[crash_log.txt](https://github.com/user-attachments/files/16236223/crash_log.txt) - Desktop
 
This is for ALVR from my PC

**Comment by ShootingKing-AM** [comment]
Any logs ?

**Comment by WavingSpark** [comment]
[crash_log.txt](https://github.com/user-attachments/files/16245010/crash_log.txt)

**Comment by WavingSpark** [comment]
i removed and added firewall settings, but it still dosent work.

it connects and disconnects saying connection timedout, and my phone is just jittering on the searching for streamer screen

**Comment by ShootingKing-AM** [comment]
Seems likes it has something to with render pipeline, can you make an issue with ALVR team (https://github.com/alvr-org/ALVR/issues) ? and ref this issue there ?
